### ISSUE TITLE
[HIPIFY][clang][build] Build failure when build against LLVM ToT 18.0.0git

### ISSUE THREAD

**Issue by emankov** [ROCm-Developer-Tools/HIPIFY#1046]
```cpp
error : 'clang::HeaderFileInfo &clang::HeaderSearch::getFileInfo(clang::FileEntryRef)': cannot convert argument 1 from 'const clang::FileEntry *' to 'clang::FileEntryRef'
```

**Comment by emankov** [comment]
Fixed by #1047.

**Comment by janhec** [comment]
I was still getting an error with 5.7, using clang 20, in HipifyAction::EndSourceFileAction(), which I found to be solved by changing to
```
    clang::FileEntryRef FR = SM.getFileEntryRefForID(SM.getMainFileID()).value();
    const clang::IdentifierInfo *controllingMacro = HS.getFileInfo(FR).getControllingMacro(EPL);

```
from
```
    const clang::FileEntry *FE = SM.getFileEntryForID(SM.getMainFileID()).value();
    const clang::IdentifierInfo *controllingMacro = HS.getFileInfo(FE).getControllingMacro(EPL);

```
In later (6+) versions I also noted
```
    auto &CI = getCompilerInstance();
    auto &SM = CI.getSourceManager();
    const clang::IdentifierInfo *controllingMacro = llcompat::getControllingMacro(CI);

```
which ended in `namespace "llcompat" has no member "getControllingMacro"`.
Class FileEntryRef is a bit strange at first because it cannot be constructed. OptionalFileEntryRef is constructable, and that is used as return  from the relevant functions.
BTW I need the older version because my GPU (AMD Radeon PRO VII) is no longer supported by ROCm after version 5.7 (and it is simply to capable to just throw away and spend a lot of money on something which performs worse for my type of use), and I believe I need a Hipify version that matches the ROCm version.

**Comment by emankov** [comment]
Why are you using such an old hippify-clang as of version 5.7? Could you try 6.4x instead?

**Comment by janhec** [comment]
Hey, I thought I explained. I need it for a AMD GPU (Radeon VII Pro) that
is not supported after Rocm 5.7 and there could be patterns in the newer
Hipify versions that do not work with the older ROCm version I have
installed for my GPU.

**Comment by janhec** [comment]
But don't worry,  I got it working, so that's ok. Just did my first (own)
.cu and with a little more, got it to compile.
Tomorrow going to see if it actually works, too😎.
